version: "3.3"
services:
  api:
    container_name: api-container
    build: .
    ports:
      - 9080:9080
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db


  db:
    container_name: mysql-container
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

#    volumes:
#      - ./mysql:/var/lib/mysql
