version: "3.3"
services:
  api:
    container_name: api-container
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database

  database:
    container_name: mysql-container
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql